import { chromium } from 'playwright';
const b = await chromium.launch({ headless: false, args: ['--window-size=1536,952','--window-position=0,0','--autoplay-policy=no-user-gesture-required'] });
const p = await b.newPage({ viewport: { width: 1536, height: 864 } });
const errs = [];
p.on('pageerror', e => errs.push('[pageerror] '+e.message));
p.on('console', m => { if (m.type()==='error'||m.type()==='warning') errs.push('['+m.type()+'] '+m.text()); });
p.on('response', r => { if (r.status()>=400) errs.push('['+r.status()+'] '+r.url()); });
const t0 = Date.now();
await p.goto('http://localhost:4173/');
await p.waitForSelector('#entry.is-ready', { timeout: 60000 });
console.log('production build 可交互耗时:', Date.now()-t0, 'ms');
await p.evaluate(() => document.getElementById('entry').click());
await p.waitForTimeout(12000);
console.log('t =', await p.evaluate(() => window.__qixi?.time?.toFixed(1) ?? 'no debug hook'));
await p.evaluate(() => window.__qixi.seek(30));
await p.waitForTimeout(2500);
await p.screenshot({ path: 'qa/shots/prod.png' });
console.log('errors:', errs.length ? [...new Set(errs)].join('\n') : 'none');
await b.close();
